#!/bin/bash
# 一键发版:测试 + tag + push + GitHub Release
set -e

# 颜色
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}=== myagent release script ===${NC}"

# 1. 读版本号
VERSION=$(cat package.json | grep '"version"' | head -1 | sed 's/.*"version": "\(.*\)".*/\1/')
echo -e "${BLUE}当前版本: ${VERSION}${NC}"

# 2. 检查 git 状态
if [[ -n $(git status --short) ]]; then
  echo -e "${YELLOW}⚠️  Working tree 有未提交改动${NC}"
  git status --short
  read -p "继续? (y/N) " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 1
  fi
fi

# 3. 跑测试
echo -e "\n${BLUE}=== 跑测试 ===${NC}"
if ! bun test 2>&1 | tail -20; then
  echo -e "${RED}❌ 测试失败,中止发布${NC}"
  exit 1
fi

# 4. 类型检查
echo -e "\n${BLUE}=== 类型检查 ===${NC}"
if ! bun run typecheck 2>&1 | tail -10; then
  echo -e "${RED}❌ 类型检查失败${NC}"
  exit 1
fi

# 5. 构建
echo -e "\n${BLUE}=== 构建 ===${NC}"
if ! bun run build 2>&1 | tail -10; then
  echo -e "${RED}❌ 构建失败${NC}"
  exit 1
fi

# 6. git tag
echo -e "\n${BLUE}=== 打 tag v${VERSION} ===${NC}"
if git tag -l "v${VERSION}" | grep -q "v${VERSION}"; then
  echo -e "${YELLOW}⚠️  Tag v${VERSION} 已存在${NC}"
  read -p "删除并重建? (y/N) " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    git tag -d "v${VERSION}"
    git push origin :refs/tags/v${VERSION}
  else
    exit 1
  fi
fi

git tag -a "v${VERSION}" -m "Release v${VERSION}

$(date -u '+%Y-%m-%d %H:%M:%S UTC')

Generated by scripts/release.sh
"

# 7. push tag
echo -e "\n${BLUE}=== Push tag ===${NC}"
git push origin "v${VERSION}"

# 8. 创建 GitHub Release
echo -e "\n${BLUE}=== 创建 GitHub Release ===${NC}"

# 自动生成 release notes
NOTES=$(cat << END
## What's Changed

### Features
- v${VERSION} 发布
- 完整功能(见 CHANGELOG.md)

### Tests
- 45+ 测试覆盖

### Documentation
- README + 7 个文档

## Installation

\`\`\`bash
git clone https://github.com/epslkslsksndnsjs-lab/myagent
cd myagent
bun install
bun run src/main.ts help
\`\`\`

See [CHANGELOG.md](CHANGELOG.md) for full details.
END
)

gh release create "v${VERSION}" \
  --title "v${VERSION} - $(date -u '+%Y-%m-%d')" \
  --notes "$NOTES" \
  --draft  # 草稿,等手动确认后发布

echo -e "\n${GREEN}✅ Done! v${VERSION}${NC}"
echo -e "${BLUE}GitHub Release: https://github.com/epslkslsksndnsjs-lab/myagent/releases/tag/v${VERSION}${NC}"
